Initialize '_tools_by_hash' at galaxy startup.
Initialize '_tools_by_hash' at galaxy startup to prevent error below (which
occurs when running a CWL workflow):
<--
File "lib/galaxy/tools/toolbox/base.py", line 435, in get_tool
   tool_id = self._tools_by_hash[tool_hash].id
KeyError: u'a35be916a3ee7d4c1eefc32c9043637d2048d1df76e4279a94f7b9c9d1367555'
-->

Notes:
- 'filter' has been replaced by 'filter_by' to prevent error below:
<--
  File "lib/galaxy/workflow/modules.py", line 771, in __init__
    trans.app.toolbox._init_dynamic_tools()
  File "lib/galaxy/tools/toolbox/base.py", line 183, in _init_dynamic_tools
    for dynamic_tool in self.app.dynamic_tool_manager.list_tools():
  File "lib/galaxy/managers/tools.py", line 117, in list_tools
    return self.query().filter(active=active)
TypeError: filter() got an unexpected keyword argument 'active'
-->
- due to above modifications, 'tool_hash' argument is now needed
when calling get_tool() method.